"""add nullable to password

Revision ID: 3ffa693e8c2d
Revises: 0f31126d56f7
Create Date: 2025-09-09 16:56:26.099962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa,sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ffa693e8c2d'
down_revision: Union[str, Sequence[str], None] = '0f31126d56f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
