"""rename

Revision ID: 6c0ad5ff4dd2
Revises: c627e6153184
Create Date: 2025-09-09 19:21:55.121973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa,sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c0ad5ff4dd2'
down_revision: Union[str, Sequence[str], None] = 'c627e6153184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_setup_steps', sa.Integer(), nullable=False))
    op.drop_column('users', 'onboarding_steps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_steps', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'profile_setup_steps')
    # ### end Alembic commands ###
