"""add attr in users

Revision ID: c627e6153184
Revises: 3ffa693e8c2d
Create Date: 2025-09-09 18:59:06.958558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c627e6153184'
down_revision: Union[str, Sequence[str], None] = '3ffa693e8c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_profile_completed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('onboarding_steps', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_steps')
    op.drop_column('users', 'is_profile_completed')
    # ### end Alembic commands ###
